version: '3.8'
services:
  nextjs:
    build: ./
    container_name: nextjs
    hostname: nextjs
    ports:
      - '3000:3000'  # Expose ứng dụng trên cổng 6869
    environment:
      - NODE_ENV=production
  nginx:
      build: ./nginx
      ports:
        - 6869:80
