version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - '3000:3000' # Next.js chạy trên cổng 3000
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80' # Nginx chạy trên cổng 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
