version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - '3000:3000'  # Next.js chạy trên cổng 3000
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '6869:80'  # Nginx chạy trên cổng 80, tiếp nhận yêu cầu HTTP từ bên ngoài
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Cấu hình cho Nginx
    depends_on:
      - nextjs  # Đảm bảo Nginx sẽ khởi động sau khi Next.js đã sẵn sàng